

CREATE TABLE dbo.EventCounterComments(

ID UNIQUEIDENTIFIER PRIMARY KEY,

UserId  UNIQUEIDENTIFIER NULL  FOREIGN KEY  (UserId) REFERENCES Users(Id),  

EventCounterId UNIQUEIDENTIFIER NOT NULL  FOREIGN KEY  (EventCounterId) REFERENCES EventCounter(Id),

CreationDate DATETIME NOT NULL,

Comment NVARCHAR(1024) NOT NULL,

Status INT NOT NULL DEFAULT 0,

IP NVARCHAR(40) NOT NULL,

Name NVARCHAR (128) NOT NULL,

ParentCommentID UNIQUEIDENTIFIER NULL, FOREIGN KEY (ParentCommentID) REFERENCES EventCounterComments(ID)

)